# R Markdown workflow | R Markdown工作流

Earlier, we discussed a basic workflow for capturing your R code where you work  interactively in the _console_, then capture what works in the _script editor_. R Markdown brings together the console and the script editor, blurring the lines between interactive exploration and long-term code capture. You can rapidly iterate within a chunk, editing and re-executing with Cmd/Ctrl + Shift + Enter. When you're happy, you move on and start a new chunk.

我们在前面讨论过一个基本的工作流，首先说明了如何在控制台中交互地使用 R 代码， 然后介绍了脚本编辑器的功能。R Markdown 将控制台和脚本编辑器结合在一起，既可以进行交互式数据探索，也可以长久保存代码。你可以在一个代码段内快速迭代，先修改代码，然后使用 Ctrl+Shift+Enter 重新运行代码。如果愿意的话，你还可以继续添加新的代码段。

R Markdown is also important because it so tightly integrates prose and code. This makes it a great __analysis notebook__ because it lets you develop code and record your thoughts. An analysis notebook shares many of the same goals as a classic lab notebook in the physical sciences. It:

R Markdown 的重要性还在于，它可以将文本和代码紧密地集成在一起。这使得它既可以开发代码，又可以记录你的想法，是一种非常棒的分析式笔记本。自然科学研究中一般都会有个实验记录本，分析式笔记本的一些用途与实验记录本是基本相同的。

*   Records what you did and why you did it. Regardless of how great your
    memory is, if you don't record what you do, there will come a time when
    you have forgotten important details. Write them down so you don't forget!
    
    • 记录你做了什么，以及为什么要这样做。不管记忆力多么强大，如果不进行记录，你总会有忘记重要事情的时候。好记性不如烂笔头！

*   Supports rigorous thinking. You are more likely to come up with a strong
    analysis if you record your thoughts as you go, and continue to reflect
    on them. This also saves you time when you eventually write up your
    analysis to share with others.
    
    • 帮助你进行更加缜密的思考。如果能在工作过程中随时记录想法并不断进行反思，那么就更有可能将分析工作做得更好。在最后归纳分析结果以便与他人分享时，这些记录还可以节省你大量的时间。

*   Helps others understand your work. It is rare to do data analysis by
    yourself, and you'll often be working as part of a team. A lab notebook
    helps you share not only what you've done, but why you did it with your
    colleagues or lab mates.
    
    • 帮助人们理解你的工作。数据分析通常不是一个人的事情，你经常会作为团队中的一员。实验记录本不但可以告诉同事或同实验室的人你做了哪些工作，还可以告诉他们你为什么要这样做。

Much of the good advice about using lab notebooks effectively can also be translated to analysis notebooks. I've drawn on my own experiences and Colin Purrington's advice on lab notebooks  (<http://colinpurrington.com/tips/lab-notebooks>) to come up with the following tips:

有效使用实验记录本的一些成熟经验完全可以推广到分析式笔记本上。根据自己的亲身体会，并结合 Colin Purrington 关于实验记录本的意见，我们给出了如下一些建议。

*   Ensure each notebook has a descriptive title, an evocative filename, and a
    first paragraph that briefly describes the aims of the analysis.
    
    • 确保每个笔记本都有一个描述性标题和一个有助于记忆的文件名，并在第 1 段中简要地介绍一下这项分析的主要目的。

*   Use the YAML header date field to record the date you started working on the
    notebook:
    
    • 使用 YAML 文件头中的日期域来记录开始使用这个笔记本的日期：

    ```yaml
    date: 2016-08-23
    ```

    Use ISO8601 YYYY-MM-DD format so that's there no ambiguity. Use it
    even if you don't normally write dates that way!
    
    使用 ISO 8601 标准的 YYYY—MM—DD 格式来避免歧义。即使通常不使用这种格式的日期，你也一定要这样做！

*   If you spend a lot of time on an analysis idea and it turns out to be a
    dead end, don't delete it! Write up a brief note about why it failed and
    leave it in the notebook. That will help you avoid going down the same
    dead end when you come back to the analysis in the future.
    
    •	对一个分析思路花费大量时间后，如果发现还是走入了死胡同，此时不要丢弃它。进行简短的笔记，记录为什么会失败，并保存在笔记本中。如果未来的某个时刻回过头来再进行这项分析时，你就可以避免重蹈覆辙。

*   Generally, you're better off doing data entry outside of R. But if you 
    do need to record a small snippet of data, clearly lay it out using
    `tibble::tribble()`.
    
    •	一般来说，我们不使用 R 进行数据录入。但如果你需要记录一小段数据的话，可以使用 tibble::tribble() 函数来录入，它非常简单直观。

*   If you discover an error in a data file, never modify it directly, but
    instead write code to correct the value. Explain why you made the fix.
    
    •	如果在某个数据文件中发现了一个错误，千万不要直接修改，而是应该通过编写代码来修改错误值，并解释为什么要进行这个修改。

*   Before you finish for the day, make sure you can knit the notebook
    (if you're using caching, make sure to clear the caches). That will
    let you fix any problems while the code is still fresh in your mind.
    
    •	在结束一天的工作前，请确认你的笔记本可以正确生成（如果使用了缓存，一定要清除）。这样可以让你趁热打铁地修改笔记本中可能存在的错误。

*   If you want your code to be reproducible in the long-run (i.e. so you can
    come back to run it next month or next year), you'll need to track the
    versions of the packages that your code uses. A rigorous approach is to use
    __packrat__, <http://rstudio.github.io/packrat/>, which stores packages 
    in your project directory, or __checkpoint__,
    <https://github.com/RevolutionAnalytics/checkpoint>, which will reinstall
    packages available on a specified date. A quick and dirty hack is to include
    a chunk that runs `sessionInfo()` --- that won't let you easily recreate 
    your packages as they are today, but at least you'll know what they were.
    
    •	如果想让代码长期可重用（也就是说，一个月或一年后这段代码依然可以运行），你需要跟踪代码中使用的 R 包的版本更新信息。一种非常好的方法是使用 packrat 包，它可以将 R 包保存到你的项目目录中。另一种方法是使用 checkpoint 包，它可以在一个特定日期重新安装所有可用的 R 包。还有一种很简便的方法，但是既不够正规，也不够优雅， 就是在笔记本中加入运行 sessionInfo() 函数的一个代码段，虽然这样不能很方便地更新 R 包，但至少可以让你知道这些 R 包现在的版本。

*   You are going to create many, many, many analysis notebooks over the course
    of your career. How are you going to organise them so you can find them
    again in the future? I recommend storing them in individual projects,
    and coming up with a good naming scheme.
    
    •	你的整个职业生涯中会创建很多很多分析式笔记本。应该如何管理它们，才能在以后找到需要的笔记本呢？我们的建议是，将它们保存在一个独立的项目中，并使用一种恰当的命名模式。
